[tool.poetry]
name = "airflow-workshop"
version = "0.1.0"
description = ""
authors = ["Marcelo Portella <marcelo.portella@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
